### PR TITLE
Nix: /embed, /notes  Limit: /likes  Combine: various regexs

### PR DESCRIPTION
**Pull request by marked**
More URL blocks:
/notes*
/embed

### CODE REVIEW

**Comment by Arkiver2** [comment]
We should be careful with this as embed URLs might be used to embed tumblr pages on other websites.

**Comment by marked** [comment]
/embed is the UI for creating embeds in other insights rather than the embed code itself.
oembed was json supposedly for remoted embed.

**Comment by Arkiver2** [comment]
Please do not add `-light` to the version. Set it to a normal version. Also please make the `/embed`, etc., ignores more specific for the cases, since this will now exclude posts that have `embed` as title in the URL. (see the title in the URL at for example http://micahulrichdraws.tumblr.com/post/180756573869/im-in-over-my-head-dearest).

**Comment by marked** [comment]
I don't see how the example URL has "/embed" in it, but I anchored it to the path location the 4th path location anyway.

**Comment by marked** [comment]
Testing...

**Comment by marked** [comment]
Testing...
/amp PASS
/notes PASS
/likes limit PASS
/embed : 
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/146207339614/embed
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/146207430634/embed

URI count 732
View .warc with Web

**Comment by marked** [comment]
Tests:
/amp none PASS
/notes none PASS
/likes 235 increasing PASS
/embed:
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/146650017964/embed
PASS
:tags  :
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/page/:page
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id/:summary
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id/
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/archive/:year/:month
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/likes/page/:page
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/archive/:year/
FAIL

**Pull request merged**
